#!/bin/bash
# Run sql
export PATH="/usr/local/bin:$PATH"
echo 'SQL'
docker-compose run --rm --no-deps -e PGOPTIONS='--client-min-messages=warning' --entrypoint psql run -h db -U robot -d robotgame -q -1 -f /sql/daily.sql
# Backup dbs
echo 'Backup dbs'
docker-compose run --rm --no-deps --entrypoint pg_dump run -h db -U robot -d robotgame --format=c -s -f /dbbackups/`date +\%Y-\%m-\%d`-robotgame-schema
docker-compose run --rm --no-deps --entrypoint pg_dump run -h db -U robot -d robotgame --format=c -a -T history -f /dbbackups/`date +\%Y-\%m-\%d`-robotgame-data
# Retore dbs
#docker-compose run --rm --no-deps --entrypoint pg_restore run -h db -U robot -d robotgame --format=c -a /dbbackups/restoredata
# Compress matches
# Note that -mtime +1 matches at least 2 days ago
# Keep for 2 weeks so fewer 404s for Google
echo 'Clean matchlog'
docker-compose run --rm --no-deps --entrypoint find run /matchlog/ -not -path "/matchlog/" -not -path "*/.gitkeep" -mtime +13 -delete;
echo 'Done'
