#!/usr/bin/env bash
set -e
echo `date`
# Go to project base.
cd "$(dirname "${BASH_SOURCE[0]}")/../" && pwd
export PATH="/usr/local/bin:$PATH"

echo 'SQL'
docker-compose run --rm --no-deps -e PGOPTIONS='--client-min-messages=warning' --entrypoint psql run -h db -U robot -d robotgame -q -1 -f /sql/daily.sql
# Backup dbs
echo 'Backup dbs'
rm -rf ./dbbackups/*
docker-compose run --rm --no-deps --entrypoint pg_dump run -h db -U robot -d robotgame --format=c -s -f /dbbackups/`date +\%Y-\%m-\%d`-robotgame-schema
docker-compose run --rm --no-deps --entrypoint pg_dump run -h db -U robot -d robotgame --format=c -a -T history -f /dbbackups/`date +\%Y-\%m-\%d`-robotgame-data
# Compress matches
# Note: -mtime +1 matches at least 2 days ago, keep 8 days to match history db
echo 'Clean matchlog'
docker-compose run --rm --no-deps --entrypoint find run /matchlog/ -not -path "/matchlog/" -not -path "*/.gitkeep" -mtime +7 -delete;
echo 'Clean containers'
docker-compose rm -f
echo 'Done'
