#!/usr/bin/env bash
set -e
echo `date`
# Go to project base.
cd "$(dirname "${BASH_SOURCE[0]}")/../" && pwd
export PATH="/usr/local/bin:$PATH"

echo 'SQL'
docker-compose run --no-deps -e PGOPTIONS='--client-min-messages=warning' --entrypoint psql run -h db -U robot -d robotgame -q -1 -f /sql/hourly.sql
echo 'Done'
